# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-29 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerceapp', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(null=True, upload_to='pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cname',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='comment',
            field=models.TextField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('CH', 'China'), ('UK', 'United Kingdom')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fname',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='lname',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='ph_number',
            field=models.IntegerField(null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(max_length=30, null='True'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.IntegerField(null='True'),
        ),
    ]
